# Generated by Django 3.2.6 on 2021-12-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Academic',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Pin',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
        migrations.AlterField(
            model_name='news',
            name='dept',
            field=models.CharField(choices=[('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Electrical', 'Electrical'), ('ComputerScience', 'Computer Science'), ('Electronics&Communication', 'Electronics & Communication'), ('Event', 'Event'), ('CDC', 'CDC')], default='Computer Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(choices=[('', 'Depertment'), ('Not Applicable', 'Not Applicable'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil '), ('Electrical', 'Electrical'), ('Computer Science', 'Computer Science'), ('Electronics & Communication', 'Electronics & Communication')], default='Computer Science', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.CharField(choices=[('', 'Semester'), ('Not Applicable', 'Not Applicable'), ('First Semester', 'First Semester'), ('Second Semester', 'Second Semester '), ('Third Semester', 'Third Semester'), ('Fourth Semester', 'Fourth Semester'), ('Fifth Semester', 'Fifth Semester'), ('Sixth Semester', 'Sixth Semester'), ('Seventh Semester', 'Seventh Semester'), ('Eightth Semester', 'Eightth Semester')], default='First Semester', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(choices=[('', 'Year'), ('Not Applicable', 'Not Applicable'), ('First Year', 'First Year'), ('Second Year', 'Second Year '), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], default='First Year', max_length=40),
        ),
    ]
